"""
Article humanizer — Claude API, Pass 2.
Rewrites the draft to remove AI-sounding patterns and add journalist voice.
Uses the same cached system prompt to save API cost.
"""
import re

from ..config import Config
from ..utils.logger import get_logger
from .article_generator import JOURNALIST_SYSTEM_PROMPT

logger = get_logger("humanizer")

# Phrases Claude commonly outputs that sound robotic
BANNED_PHRASES = [
    "delve", "delving", "delved",
    "crucial", "pivotal", "paramount",
    "landscape", "realm", "sphere",
    "testament to", "it's worth noting",
    "it is important to note",
    "in today's fast-paced",
    "needless to say",
    "in conclusion",
    "to summarize",
    "in summary",
    "at the end of the day",
    "game-changer", "game changer",
    "paradigm shift",
    "holistic approach",
    "stakeholders",
    "leverage" ,    # when used as a verb meaning "use"
    "foster",
    "underscore",
    "navigate",
    "empower",
    "unlock",
]

HUMANIZE_SYSTEM = """You are an editor at a top Indian financial newspaper. Your job is to rewrite AI-generated drafts to sound authentically human — like they were written by a seasoned journalist, not generated by software."""


def _build_humanize_prompt(draft: str, config: Config) -> str:
    banned_list = "\n".join(f"- {p}" for p in BANNED_PHRASES)
    return f"""Rewrite the article below to sound more human and journalistic. Follow these rules EXACTLY:

RULES:
1. Vary sentence length dramatically — the article must mix 5-word sentences with 25-word ones
2. Add 2 rhetorical questions at natural points (not just at the end)
3. Replace ALL passive voice constructions with active voice
4. Remove every instance of these banned phrases/words:
{banned_list}
5. Add one India-specific analogy or example that will resonate with local readers
6. Keep ALL numbers, data points, and the FAQ section exactly as written
7. Keep the legal disclaimer exactly as written
8. Do NOT add new facts or remove any existing facts
9. Target: {config.target_word_count_min}–{config.target_word_count_max} words (you can be within ±5%)
10. Maintain all H2/H3 headings (you may tweak wording slightly)

ARTICLE TO REWRITE:
{draft}

OUTPUT: The rewritten article in the same markdown format."""


def _count_banned_phrases(text: str) -> int:
    text_lower = text.lower()
    return sum(1 for phrase in BANNED_PHRASES if phrase in text_lower)


def _humanness_score(text: str) -> float:
    """
    Heuristic score 0.0–1.0. Higher = more human.
    Penalises: banned phrases, long uniform sentences, low question count.
    """
    banned_count = _count_banned_phrases(text)
    sentences = [s.strip() for s in re.split(r'[.!?]+', text) if s.strip()]
    if not sentences:
        return 0.0

    avg_len = sum(len(s.split()) for s in sentences) / len(sentences)
    lengths = [len(s.split()) for s in sentences]
    variance = sum((l - avg_len) ** 2 for l in lengths) / len(lengths)

    question_count = text.count("?")

    score = 1.0
    score -= min(banned_count * 0.08, 0.5)    # up to -0.5 for banned phrases
    score -= max(0, (15 - variance) * 0.01)   # low variance = uniform = robotic
    score += min(question_count * 0.05, 0.15) # reward questions

    return max(0.0, min(1.0, score))


async def humanize_article(draft: str, config: Config, max_attempts: int = 2) -> str:
    """
    Run the humanize pass. Returns the best version or original draft if AI fails.
    Runs API call in thread pool to avoid blocking uvicorn's event loop.
    """
    import asyncio

    best_text = draft
    best_score = _humanness_score(draft)
    logger.info(f"Draft humanness score: {best_score:.2f}. Running humanize pass…")

    def _single_pass(text: str) -> str:
        client = config.make_ai_client()
        prompt = _build_humanize_prompt(text, config)
        response = client.chat.completions.create(
            model=config.ai_model,
            max_tokens=5000,
            messages=[
                {"role": "system", "content": HUMANIZE_SYSTEM},
                {"role": "user", "content": prompt},
            ],
        )
        return (response.choices[0].message.content or "").strip()

    loop = asyncio.get_event_loop()
    for attempt in range(max_attempts):
        try:
            result = await asyncio.wait_for(
                loop.run_in_executor(None, _single_pass, best_text),
                timeout=120.0
            )
            if not result:
                break
            score = _humanness_score(result)
            word_count = len(result.split())
            logger.info(f"Humanize attempt {attempt + 1}: score={score:.2f}, words={word_count}")
            if score > best_score:
                best_score = score
                best_text = result
            if score >= 0.70:
                logger.info("Humanness threshold met.")
                break
        except Exception as e:
            logger.warning(f"Humanize attempt {attempt + 1} failed ({e}) — using best so far")
            break

    banned_remaining = _count_banned_phrases(best_text)
    if banned_remaining > 0:
        logger.warning(f"{banned_remaining} banned phrase(s) still remain after humanization")
    return best_text
