"use client"

/**
 * Awaiting Review queue — every article generated by the pipeline lands here
 * as a WordPress DRAFT and waits for human approval before going public.
 *
 * Hits GET /api/py/runs/pending-review every 10 seconds.
 * Each row links to /dashboard/runs/[id]/article which shows the full
 * review banner with Approve / Reject / Preview / WP Admin buttons.
 */

import { useEffect, useState } from "react"
import Link from "next/link"

type FactFlag = { severity: string; category: string; snippet: string; detail: string }
type FactValidation = {
  is_clean: boolean
  high_severity_count: number
  flag_count: number
  summary: string
  flags: FactFlag[]
}

type PendingRun = {
  run_id: string
  topic?: string
  topic_meta?: { title?: string; category?: string }
  article_word_count?: number
  wp_post_id?: number
  wp_preview_url?: string
  wp_admin_url?: string
  fact_validation?: FactValidation
  started_at?: string
  created_at?: string
}

type PendingResponse = { count: number; runs: PendingRun[] }


function timeAgo(iso?: string): string {
  if (!iso) return "—"
  const then = new Date(iso).getTime()
  if (Number.isNaN(then)) return "—"
  const seconds = Math.floor((Date.now() - then) / 1000)
  if (seconds < 60)  return `${seconds}s ago`
  if (seconds < 3600) return `${Math.floor(seconds / 60)}m ago`
  if (seconds < 86400) return `${Math.floor(seconds / 3600)}h ago`
  return `${Math.floor(seconds / 86400)}d ago`
}


export default function ReviewQueuePage() {
  const [data, setData]       = useState<PendingResponse | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError]     = useState<string | null>(null)

  async function load() {
    try {
      const res = await fetch("/api/py/runs/pending-review", { cache: "no-store" })
      if (!res.ok) throw new Error(`HTTP ${res.status}`)
      setData(await res.json())
      setError(null)
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e))
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    load()
    const id = setInterval(load, 10_000)
    return () => clearInterval(id)
  }, [])

  return (
    <div className="max-w-5xl pb-24">
      <header className="mb-6">
        <h1 className="text-[20px] font-semibold text-neutral-100">Awaiting Review</h1>
        <p className="text-[13px] text-neutral-500 mt-1">
          Articles generated by the pipeline are saved as WordPress drafts here.
          They become public <b className="text-neutral-300">only after you read and approve them</b>.
        </p>
      </header>

      {loading && (
        <div className="text-[13px] text-neutral-500">Loading queue…</div>
      )}

      {error && (
        <div className="rounded-lg border border-red-500/40 bg-red-500/5 p-4 text-[13px] text-red-300">
          Failed to load: {error}
        </div>
      )}

      {!loading && data && data.count === 0 && (
        <div className="rounded-xl border border-neutral-800 bg-neutral-900/40 p-10 text-center">
          <div className="mx-auto h-12 w-12 rounded-full bg-emerald-500/10 flex items-center justify-center mb-3">
            <svg className="h-6 w-6 text-emerald-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M4.5 12.75l6 6 9-13.5" />
            </svg>
          </div>
          <div className="text-[14px] font-semibold text-neutral-200">All caught up</div>
          <div className="text-[12px] text-neutral-500 mt-1">
            No drafts are waiting for review. New articles will appear here after generation.
          </div>
          <Link href="/dashboard/queue" className="inline-block mt-4 text-[12px] text-red-400 hover:text-red-300">
            Go to topic queue →
          </Link>
        </div>
      )}

      {data && data.count > 0 && (
        <div className="space-y-3">
          {data.runs.map(run => {
            const title = run.topic_meta?.title || run.topic || run.run_id
            const cat   = run.topic_meta?.category || ""
            const fv    = run.fact_validation
            const hasFlags = fv && fv.flag_count > 0
            const isHighFlag = fv && fv.high_severity_count > 0

            return (
              <Link
                key={run.run_id}
                href={`/dashboard/runs/${run.run_id}/article`}
                className="block rounded-xl border border-neutral-800 bg-neutral-900/40 hover:bg-neutral-900/70 hover:border-neutral-700 transition-colors p-4"
              >
                <div className="flex items-start gap-4">
                  <div className="rounded-full bg-amber-500/15 p-2 shrink-0">
                    <svg className="h-4 w-4 text-amber-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                      <path strokeLinecap="round" strokeLinejoin="round" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
                    </svg>
                  </div>

                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 flex-wrap">
                      {cat && (
                        <span className="text-[10px] font-semibold uppercase tracking-wider text-neutral-500">
                          {cat}
                        </span>
                      )}
                      <span className="text-[11px] text-neutral-600">
                        Generated {timeAgo(run.started_at || run.created_at)}
                      </span>
                      {typeof run.article_word_count === "number" && (
                        <span className="text-[11px] text-neutral-600">·  {run.article_word_count} words</span>
                      )}
                    </div>
                    <h2 className="text-[14px] font-semibold text-neutral-100 mt-1 line-clamp-2">
                      {title}
                    </h2>

                    {/* Fact-validator pill */}
                    {fv && (
                      <div className={`inline-flex items-center gap-1.5 mt-2 rounded-md px-2 py-1 text-[11px] font-medium ${
                        isHighFlag
                          ? "bg-red-500/15 text-red-300 border border-red-500/30"
                          : hasFlags
                          ? "bg-amber-500/10 text-amber-300 border border-amber-500/20"
                          : "bg-emerald-500/10 text-emerald-300 border border-emerald-500/20"
                      }`}>
                        {isHighFlag ? "⚠ Requires attention" : hasFlags ? "⚑ Some flags" : "✓ Fact-clean"}
                        <span className="opacity-70">·  {fv.summary}</span>
                      </div>
                    )}
                  </div>

                  <div className="flex flex-col items-end gap-2 shrink-0">
                    <span className="rounded-md bg-amber-500/15 text-amber-300 px-2.5 py-1 text-[10px] font-semibold uppercase tracking-wider border border-amber-500/30">
                      Awaiting review
                    </span>
                    <span className="text-[12px] text-neutral-400 group-hover:text-neutral-200">
                      Review →
                    </span>
                  </div>
                </div>
              </Link>
            )
          })}
        </div>
      )}
    </div>
  )
}
